### ISSUE TITLE
Uncaught TypeError: this.updater.enqueueCallback is not a function at CurrencyInput

### ISSUE THREAD

**Issue by francisrod01** [jsillitoe/react-currency-input#60]
My implementation is below:

App.js

```js
...
    const numberOpts = {
      style: 'currency',
      currency: 'BRL',
      thousandSeparator: '.',
      decimalSeparator: ',',
      digits: 2,
      prefix: '$',
      sufix: null,
    }
```

MyComponent.js

```js
handleChangePrice(event, maskedValue, floatValue) {
    event.preventDefault()

    console.log('handle change price: ', maskedValue, floatValue)
}

<CurrencyInput
  className='form-control'
  ref='price'
  onChangeEvent={this.handleChangePrice}
  value={srv.price}
  thousandSeparator={this.props.numberOpts.thousandSeparator}
  decimalSeparator={this.props.numberOpts.decimalSeparator}
  precision={this.props.numberOpts.digits}
  prefix={this.props.numberOpts.prefix}
  sufix={this.props.numberOpts.sufix}
  />
```

and the output was:

```
Uncaught TypeError: this.updater.enqueueCallback is not a function
    at CurrencyInput../node_modules/react-currency-input/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (http://localhost:3000/static/js/bundle.js:53711:18)
    at CurrencyInput.handleChange (http://localhost:3000/static/js/bundle.js:36004:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:60275:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:60314:16)
    at Object.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:60171:27)
    at Object.invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:60185:43)
```

What's happening?

**Comment by bvanderdrift** [comment]
The project does not support React16 yet, which I guess you are running. You can check this with `npm ls react`. Due to a version mismatch this error gets thrown as in https://github.com/facebook/react/issues/10320.

**Comment by bvanderdrift** [comment]
Seems they have already fixed the issue in https://github.com/jsillitoe/react-currency-input/pull/56 but not published it to npm yet.

**Comment by leonardo031195** [comment]
+1

**Comment by mikdatdogru** [comment]
+1

**Comment by hermesnetto** [comment]
+1

**Comment by dimoreira** [comment]
+1

**Comment by dankirlin** [comment]
+1

**Comment by savacristian** [comment]
+1

**Comment by selected-pixel-jameson** [comment]
+1

**Comment by sebastianrjay** [comment]
+1

**Comment by jsillitoe** [comment]
Published the fix.  Should work now.
